Extend slideshow block with source option
pixelgrade/nova-blocks pull request #295
Opened 2021-02-24 12:16 UTC by madalingorbanescu

2021-02-25 12:56 UTC, razwan requested changes

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/preview.js
> +    let slide = getGallerySlideData( galleryImages, this.props );
```js
let slides = getSlidesFromGalleryImages( ...
```

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/edit.js
>  					previewImage={ galleryImages[ selectedIndex ] }
selectedIndex seems to still be relevant for editing the focal point for each image, you could try to refactor this component into a functional component and use `useState()` for cleaner code

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/edit.js
>  					previewImage={ galleryImages[ selectedIndex ] }
setIndex function passed to the GalleryPreview component inside InspectorControls should also trigger slick to go to that specific slide

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/frontend.js
> -		$block.find( SLIDE_SELECTOR ).each( function( i, obj ) {
each should iterate over `SLIDE_SELECTOR` and not `SLIDER_SELECTOR`

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/init.php
> +
There should be a check for when there are no slides and not output and / or initialize the slider in this case.

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/edit.js
>  				<InspectorControls { ...{ ...newProps, setIndex, selectedIndex } } />
Change Media button should not be displayed inside block controls when the source attribute is set to posts

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/init.php
> +	$width = $thumbnail['sizes']['large']['width'];
There is the change for the attachment not having the large image size.

Markup output should be abstracted into a function that receives $image or $image_id and $content and outputs them with the proper wrappers:
```php
	<div class="<?php echo esc_attr( $className ); ?>">
		<div class="novablocks-slideshow__slide-wrap">
			<div class="novablocks-slideshow__background novablocks-u-background">
				<div class="novablocks-mask">
					<div class="novablocks-parallax">
					    <?php novablocks_output_slideshow_slide_background( $image or $image_id ); ?>
					....
			<div class="novablocks-slideshow__foreground novablocks-foreground novablocks-u-content-padding novablocks-u-content-align">
				<div class="novablocks-slideshow__inner-container novablocks-u-content-width">
				<?php echo $content; ?>
				...
```
in order to not repeat yourself and have consistent markup for both use cases

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/inspector-controls.js
> +const MetaSource = ( props ) => {
MetaSource and ToggleGroup should be moved inside a hook in the block-editor package. the ToggleGroup component should receive a function through props in order to filter the displayed toggles. At the same time, attributes needed for these components should be moved to that hook as well.

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/preview.js
> +             <Slider className="novablocks-slideshow__slider" {...sliderSettings}>
You should start with this. For cleaner code you should split the two use cases into separate components like so.
```js
            <GallerySlider { ...props } />
            <PostsSlider { ...props } />
```

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/preview.js
> +        <Slide id={id} className="novablocks-slideshow__slide" {...props} image={ wp.data.select( 'core').getMedia(post.featured_media) } post={ post } type="post"/>
the image prop should be standardized before passing it to the Slide component and not inside it

2021-02-25 12:56 UTC, razwan commented on packages/block-library/src/blocks/slideshow/preview.js
> +        <Slide id={id} className="novablocks-slideshow__slide" {...props} image={ wp.data.select( 'core').getMedia(post.featured_media) } post={ post } type="post"/>
Also... the best case scenario is when the Slide component receives only two props `media` and `content`. You could try to reach this scenario

2021-04-12 10:42 UTC, madalingorbanescu commented
I am going to close this PR because those changes were moved on `try/supernova-block` branch.

2021-04-12 10:42 UTC, closed without merging